try again

diff --git a/.github/workflows/relevant-warnings.yml b/.github/workflows/relevant-warnings.yml
--- a/.github/workflows/relevant-warnings.yml
+++ b/.github/workflows/relevant-warnings.yml
@@ -26,11 +26,14 @@ jobs:
       - name: Install Requirements
         run: |
           pip install -r requirements.txt
+
       - name: Install libssl (overwatch-cli requires OpenSSL 1.1)
         run: |
           sudo apt-get update
-          wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
-          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
+          sudo apt-get install -y libssl1.1 || sudo apt-get install -y libssl-dev
+          sudo ldconfig  # Ensure the system's shared library cache is updated
+          # Verify OpenSSL installation
+          openssl version || echo "OpenSSL installation failed"
 
       - name: Install Static Analysis Tools
         run: |
